//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.27 at 06:20:33 PM CET
//

@jakarta.xml.bind.annotation.XmlSchema(
		namespace = "urn:oasis:names:tc:SAML:1.0:protocol",
		xmlns = {
			@jakarta.xml.bind.annotation.XmlNs(prefix="samlp", namespaceURI="urn:oasis:names:tc:SAML:1.0:protocol"),
			@jakarta.xml.bind.annotation.XmlNs(prefix="saml", namespaceURI="urn:oasis:names:tc:SAML:1.0:assertion")
		},
		elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED
	)
package urn.oasis.names.tc.saml.protocol;
